Repository akshaykumar23399/hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#2 Create Permutation.java
  Permutation.java
Labels: hactoberfest-2021

#1 Create python.py
  python.py
Labels: hactoberfest, hactoberfest-2021

#5 Create Pattern.java
  Java/Pattern.java
Labels: hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#4 Create Jframes.java
  Java/Jframes.java
Labels: hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#3 Create Strings.java
  Java/Strings.java
Labels: hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#6 Calculator.py
  Calculator.py
Labels: hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#7 Create factor.java
  factor.java
Labels: hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#11 Portfolio template
  C/Bubble_Sort.c
  C/Linkedlist.c
  Java/Reverse Linked List.java
  Protfolio/README.md
  Protfolio/_config.yml
  Protfolio/index.html
  Protfolio/style.css
Labels: good first issue, hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#9 node static file http server
  node/server.js
Labels: hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#8 Javascript program to generate random number
  JavaScript/Random.js
Labels: hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#12 Updated Readme.md
  readme.md
Labels: documentation, hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021

#13 Doubly_Linkedlist.py
  Python/Doubly_Linkedlist.py
Labels: enhancement, hactoberfest, hactoberfest-2021, hacktoberfest-accepted, hacktoberfest, hacktoberfest2021
